### ISSUE TITLE
ISO PDF: clause reference is "Clause N" but "N.n.n"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#180] opened 2020-05-08 05:20 UTC
Clauses => "Clause N".

Subclauses => "N.n.n"

This illustrates the problem in PDF:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/11865/81373126-93a7eb00-912e-11ea-9af8-648a53a132d0.png">

**Comment by Intelligent2013** [comment] 2020-05-09 12:09
@ronaldtse Could you specify which xml document did you process?

I can't reproduce it. The similar thing for ISO-690 example processed ok:
![изображение](https://user-images.githubusercontent.com/5559926/81473386-c1606300-9206-11ea-8a3a-5bbf57aa42e1.png)

**Comment by ronaldtse** [comment] 2020-05-09 16:27
The issue is from https://gitlab.com/calconnect/tc-localization/csd-transcription-systems but it's using the git gems, but not the latest PDF stylesheets.

**Comment by Intelligent2013** [comment] 2020-05-10 08:46
Yes, in CSD xslt template there is this issue.
But on development stage (3 month ago) I saw this is original docx:
![изображение](https://user-images.githubusercontent.com/5559926/81494715-a39d0780-92b3-11ea-81de-9c2080c7eb95.png)

>Clauses => "Clause N".
>Subclauses => "N.n.n"

Do you need to change these rules for all flavors, or for CSD only?

**Comment by ronaldtse** [comment] 2020-05-10 08:52
@Intelligent2013 this was a bug. 

> Clauses => "Clause N", Subclauses => "N.n.n"

Applies to all flavors that use the "Clause ..." structure. Can @opoudjis help confirm? Thanks!

**Comment by opoudjis** [comment] 2020-05-18 02:15
>> Clauses => "Clause N", Subclauses => "N.n.n"
> Applies to all flavors that use the "Clause ..." structure. Can @opoudjis help confirm? Thanks!

This is an idiosyncratic ISO rule, to drop "Clause" in front of subclauses; you can assume it for flavours inheriting from ISO (IEC, GB), but I have *not* assumed it outside of those flavours, and I do not believe we should, unless that behaviour is explicitly specified. It is not the correct behaviour in ITU, for instance:

ITU G.650 clause 6.1.1.1

> The mode field diameter is determined from the far-field intensity distribution F2(), according to the definition given in clause 3.4.1.4.

**Comment by ronaldtse** [comment] 2020-05-18 05:36
It makes me wonder whether this reference text “Clause X”, “N.n.n” should exist in the xml.

**Comment by Intelligent2013** [comment] 2020-05-18 12:21
> It makes me wonder whether this reference text “Clause X”, “N.n.n” should exist in the xml.

In this case we need also text "X" "X.n.n" for each `clause` element. In the current version of xslts I calculate "X", "X.n.n" by position of `clause`, `term`, `references` elements in xml body.

**Comment by ronaldtse** [comment] 2020-06-08 09:05
I think the labels will be dealt with in the Presentational XML work https://github.com/metanorma/metanorma-standoc/issues/285 .

**Comment by Intelligent2013** [comment] 2020-07-29 11:28
Fixed in presentation XML.

**Closed by Intelligent2013** 2020-07-29 11:28 UTC
Labels: bug
